### ISSUE TITLE
пакет не устанавливается с хаба пакетов

### ISSUE THREAD

**Issue by petypen** [khorevaa/advanced-logos#3]
Добрый день.

Выполняю установку пакета по инструкции:
`opm install advanced-logos`

получаю сообщение об ошибке:
# opm install advanced-logos
{Модуль C:\Program Files\OneScript\lib\opm\src\core\Классы\МенеджерПолученияПакетов.os / Ошибка в строке: 18 / Ошибка установки пакета advanced-logos: Пакет не найден}

**Comment by khorevaa** [comment]
Да пакет не опубликован в хабе. Т.к. не доделан. Думаю что и не будет опубликован, т.к. доделывать не собираюсь. если только найдется тот кто доделает.
